baseURL: https://evafu.netlify.app
languageCode: en-us
title: Know_about_Evafu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      GET TO KNOW ME BY THIS WEBSITE
    title: Hi, my name is Eva
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Lisson Grove
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yfu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (0741) 0451-774
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/evafu/individual_website
      - icon: fa-instagram
        label: Instagram
        url: https://www.instagram.com/evvafuu/
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.com/in/eva-yuning-fu/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs

    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: to HOME
    title: BACK
  tiles:
    enable: yes
    showcase:
      - image: Eva.jpg
        subtitle: I'm a girl from China, in LBS MFA2022
        title: About me
        url: blogs/me
      - image: Smile.jpg
        subtitle: Final R-project designed by Group B2
        title: New course I took in LBS
        url: blogs/group
      - image: London.jpg
        subtitle: See beautiful London photed by myself
        title: New life in London
        url: blogs/magna
      - image: Shanghai.jpg
        subtitle: Shanghai
        title: My dream city in China
        url: blogs/tempus
      - image: Milktea.jpg
        subtitle: This is a Chinese style milk tea
        title: My favorate drink
        url: blogs/aliquam
      - image: Experience.jpg
        subtitle: Click here to see my working experience
        title: My experience in Finance
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "I am Eva, currently reading MFA2022 in LBS. Before, I specialised in Finance & Economics in HKBU and Business Communication in University of Victoria (Canada).I have accumulated work experience in Investment Banking, Private Fund, TMT Equity Research, and Financial Product during internship at CITICS, Flying Tiger investment Inc., Guotai Junan and ICBC.I'm currently seeking internships in banking sectors in both HK and London. 

Please feel free to contact me via:
Email: yfu.mfa2022@london.edu"

    title: This is me!
    url: blogs
