baseURL: https://evafu.netlify.app
languageCode: en-us
title: Know_more_about_Evafu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      GET TO KNOW ME BY THIS WEBSITE
    title: Hi, my name is Eva
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Lisson Grove
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yfu.mfa2022@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (0741) 045-1774
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: https://www.html5up.net
    social:
      - icon: fa-github
        label: GitHub
        url: https://github.com/evafu/individual_website
      - icon: fa-linkedin
        label: LinkedIn
        url: linkedin.com/in/eva-yuning-fu
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
    menu: Menu
    subtitle: By HTML5 Up
    title: Forty
  tiles:
    enable: yes
    showcase:
      - image: Eva.jpg
        subtitle: I'm a girl from China, who is reading Masters in Financial Analysis in LBS
        title: About me
        url: blogs/me
      - image: Smile.jpg
        subtitle: The sample project for risk_return relationship
        title: New course I took in LBS
        url: blogs/risk_return
      - image: London.jpg
        subtitle: See beautiful London photed by myself
        title: New life in London
        url: blogs/magna
      - image: Shanghai.jpg
        subtitle: Shanghai
        title: My dream city in China
        url: blogs/tempus
      - image: Milktea.jpg
        subtitle: This is a Chinese style milk tea
        title: My favorate drink
        url: blogs/aliquam
      - image: Experience.jpg
        subtitle: Click here to feel free to see my working experience
        title: My internship experience
        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Motivated LBS MFA2022 student. \n    Specialised in Finance & Economics in HKBU and Business Communication in University of Victoria (Canada). \n    Accumulated work experience in Investment Banking, Private Fund, TMT Equity Research, and Financial Product during internship at CITICS, Flying Tiger investment Inc., Guotai Junan and ICBC. \n    Currently seeking internships in banking sectors in both HK and London.\n    

Please feel free to contact me via:
Email: yfu.mfa2022@london.edu
Phone:+44 07410451774/ +86 13104749091"
      
    title: This is me!
    url: blogs
